<<<<<<< HEAD
// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// import org.junit.Test;
// import static org.junit.Assert.*;
//
// public class AppTest {
//     @Test public void testAppHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }
=======
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
>>>>>>> ae11788a4d6b87c8e57cccc8332aa702800c0167
